"""add country and city to listing

Revision ID: 075e6dd83fe4
Revises: a5d598ae407e
Create Date: 2026-09-23 15:30:08.454681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075e6dd83fe4'
down_revision = 'a5d598ae407e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=30), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
