""" erased had_accident column from Listings table 

Revision ID: 0890617902a1
Revises: fec7be2c1717
Create Date: 2026-07-28 19:33:14.167990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0890617902a1'
down_revision = 'fec7be2c1717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('had_accident')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('had_accident', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
