"""empty message

Revision ID: 15b45f60999f
Revises: 45b307068279
Create Date: 2026-09-23 13:29:16.518350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b45f60999f'
down_revision = '45b307068279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=30), server_default='individual', nullable=False))
        batch_op.drop_column('seller_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_type', sa.VARCHAR(length=30), server_default=sa.text("'individual'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
