"""added mileage , indexes and changed some nullables in Listing table 

Revision ID: 1cea1507bbb0
Revises: 0e6b60b2c0d7
Create Date: 2026-07-28 18:48:16.414471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cea1507bbb0'
down_revision = '0e6b60b2c0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('fabrication_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fuel_ef',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_listing_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_status'))
        batch_op.alter_column('fuel_ef',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fabrication_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
