"""empty message

Revision ID: 45b307068279
Revises: c09311dbe203
Create Date: 2026-09-23 11:41:02.766110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b307068279'
down_revision = 'c09311dbe203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('seller_type', sa.String(length=30), server_default='individual', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('seller_type')
        batch_op.drop_column('website_url')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
