""" added configuration to listing table and changed some names 

Revision ID: 93d3905e0ece
Revises: 0890617902a1
Create Date: 2026-07-31 17:57:51.829471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d3905e0ece'
down_revision = '0890617902a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('configuration', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('power', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('displacement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuel_efficiency', sa.Float(), nullable=True))
        batch_op.drop_column('horsepower')
        batch_op.drop_column('fuel_ef')
        batch_op.drop_column('fabrication_year')
        batch_op.drop_column('price_usd')
        batch_op.drop_column('engine_displacement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_displacement', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_usd', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fabrication_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fuel_ef', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('horsepower', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('fuel_efficiency')
        batch_op.drop_column('displacement')
        batch_op.drop_column('power')
        batch_op.drop_column('year')
        batch_op.drop_column('configuration')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
