"""added other make and other model columns do listing table

Revision ID: abdc5742add9
Revises: a67234e791b7
Create Date: 2026-08-01 00:33:33.649001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdc5742add9'
down_revision = 'a67234e791b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_make', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('other_model', sa.String(length=40), nullable=True))
        batch_op.alter_column('make_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('make_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('other_model')
        batch_op.drop_column('other_make')

    # ### end Alembic commands ###
