"""added transmission , fuel type and drivetrain characteristics to listing table

Revision ID: fec7be2c1717
Revises: 1cea1507bbb0
Create Date: 2026-07-28 19:04:17.810547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec7be2c1717'
down_revision = '1cea1507bbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drivetrain', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('transmission')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('drivetrain')

    # ### end Alembic commands ###
